[package]
name = "the-great-purple-wall"
version = "0.1.0"
authors = ["Kenny Do <kedo@patreon.com>"]

[dependencies]
html5ever = "0.22.2"
hyper = "0.11.25"
hyper-tls = "0.1.3"
futures = "0.1"
tokio-core = "0.1"
kuchiki = "0.7.0"
regex = "0.2.10"
rocket = "0.3.8"
rocket_codegen = "0.3.8"
